language: node_js
node_js:
- lts/*
script:
- "./bin/d2-style js check --all"
- yarn test
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: F0lPv24woYVVE/vUs4hm6wbVYsQPLPMBcJNj30/1SmkQKNHGl+WNsV0OdFqlUnAIW01BXQvSkcdGevzy5/x4k7Xnlxj5cRiNmtwOSXIyf92nKlbCwY7J2EvQajBQKJDrA2fv3f/eaU8VdGrILn4jjrcoFM/nklp0N2FSJ4e7qEsHO628yI9Iyq7zT9gsyYgIaHzJaAvuQagubjxim/qaZBnHD6z/tWapE/CtorumpkpQk8gGjBx2FjWfPACILrbwSf5JWFpRRGWz+dziqCwsDcpHTPxFj1eVIB9iTEpSXo7nlf/qkC8lCnLtDGS4aaUrlxZMR7en/DWtLnOi6k4Mlchgx3gX477eLtACCexnMH3yTbw5JiKoY66nI8bfk7ff84nv3dOW/dUGGR3BIr3PHk4r6dRHU0z/RGWvLpwO4UdAjngkTR0MjYFEr+86RYPGKpUYwj7ej2rWMCD1hTkYVNHBB9esHwT6t7ubZkQcfc/qejgJ4CpCIF+XWe4cdBlOLo1oxKp0gVxL0gss+l9AMZS8kn0epF8mTa1yAmmb9ClD7P2LUtndeOvioA9wBU7YTIIXVLClLVPGybGCM1lXyiO1F4JO1HvCwPJr/5vT+Bo5wugvbqzNit719GtilUGHoa9G/sm4HXFf6ULmttjrmoE+7rtRT3ww5kpmCqRkyxk=
  - secure: fSDdC0HxxRh/uRta3fJjHIPt7Unq3oddaXgBN3hdXyvjVFGqgE0jVmftpMMaGka2qTAVq3V01aUAlVzOO03SxBH4Sn5LyMCvI9ZG6cDQsqeh/k1ySKOtu/iIVN1Us+IdMCq/HbhhiRVrLrBc+V6om8mVrmArrDHENOqkfq3HH4Y9Zs9x91iyOPuYIAOjjbYmVsSjSA0u5nsp2GcxX82YvcLGcwXkoK1ejUzhFQFTdRqaraiVNKUJ28jYOHizYgwKZzJmKaegTjB12AIglncfqMffPdeM6m0FzEwleKMwoFqo8/FMYynT2eRgZnHx4FXCXbFyP0kICdCOUyP5a+Qw0L9RurrJkTfDtnNVakEfw7sxduvKPfG5imlmJwEZ4pFUP1lC0PBGRqZl/tNt9jLpN8rjfVb5hRR+kPNVq1kQI02rgJEi9KGZHOP7riGlWZDgqfWOkkcPLCF5rCiyTx5thyKUYFhbNoSe7/lsMUpcyeCL7ZLbtyTn7LVQA/58ccm59kVlUoDBEcXgcl79mXWvb1pRHONgsdfWII+JnmLtyN229hNb1zSxe9N8R3+GJC7YAPxKF5XX+D+Cys9yNW87okqfZzHftPf/Xz3eZ8Csptsvx0HTNQxz0h23PUpsUfTZhY3F5RTRWMwYNnTfAsoBqne+tcOvqF0hI8GWNeAup8Q=
