language: node_js
node_js:
- 10
before_script:
- npm install --global @dhis2/deploy-build
script:
- ./bin/d2-style js check --all
deploy:
- provider: script
  script: publish-build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: HZIxsw268cQ+HAnxzPboVrpCJxcB58F9jPplxj01RJGT7UTS2Qws+efPnY8IVIKHGjgZdcWCrIb0Wp1l2lIrfq6utHYr+LqX5Ir6w8j76nVUyk5XZLe1VlMXvCpcg9eKsdh3Rup12mZQ8acA9EVPdqNk5ScE/WIQRSNfgi3eUDvm3lIMgWUt9EAyAfb88wtH+1Rw8WshLl40gXcmhNN6oZLItnuMat6VtSUfQvLKTQ3KrgFwCkl5Wp5Ag5o/zPCsaKCuKkmkeGs47rWvgaDTLcXmzUZlpG/PpIkyRWwLSVMlXWkiEirDyYdKrlz5yPwkuMB5Zip6nSS3us60rxVpZ+ixedX340Y4gmuOEhoBmR8cOzobRUfU4PxK/jQv7QPMa/2vuA0R0QyHqc+v38sIogd1JqQdCVffQNKY76kRGaDzrJ3CHo1Emh9or+pNT4Xs7qYIaBrzrj3J/OR7SdNfvy2yVKO8RQalOPDDj+Otoig6JFpM3Eb/xek57BVy5EOwOvqRxmPzQTrw6yh+6eS6Qo/1R9FXQmR6oWIHxauzwsPbrh6bXpm44X7ipDl76l4j/6XbQhbvZ6tOMY2W7u0/w2yV5ADWG1ulkhWE59xCjLsFEXrtwZs4JMqxfgD6sSxG5QO3CidL9Rc1RD4I1ABbuSuJ+WTRuGqMvOUD6jWhFNE=
