commit-msg:
    commands:
        lint-commit-msg:
            run: npx d2-style commit check

pre-commit:
    parallel: true
    commands:
        lint-javascript:
            glob: "*.{js,jsx}"
            run: npx d2-style js check {staged_files}
