name: 'dhis2: verify (node)'

# Requirements:
#
# - Org secrets:
#       DHIS2_BOT_GITHUB_TOKEN
#       DHIS2_BOT_NPM_TOKEN

on:
    push:
        branches:

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Test
              run: yarn test

    publish:
        runs-on: ubuntu-latest
        needs: [lint, test]
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
            - uses: actions/setup-node@v2
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-npm: true
                  publish-github: true
                  github-token: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
                  npm-token: ${{secrets.DHIS2_BOT_NPM_TOKEN}}
