name: DHIS2 JavaScript Library

on:
  push:
    branches:
      - master

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - uses: actions/upload-artifact@v1
        with:
          name: archive
          path: .

  test:
      name: Test
      needs: prepare
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v1
          with:
            name: archive
            path: .
        - uses: actions/setup-node@v1
          with:
            node-version: 10.x
        - run: yarn test
        - run: ./bin/d2-style js check --all

  publish-npm:
    needs: test
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: archive
          path: .
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npx @dhis2/cli-utils release --publish npm
        env:
          GIT_AUTHOR_NAME: "@dhis2-bot"
          GIT_AUTHOR_EMAIL: "apps@dhis2.org"
          GIT_COMMITTER_NAME: "@dhis2-bot"
          GIT_COMMITTER_EMAIL: "apps@dhis2.org"
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
