name: 'DHIS2: Pull Request'

on: pull_request

jobs:
  pr:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install and test
        run: |
          yarn install
          yarn test
          ./bin/d2-style js check --all
