name: Publish DHIS2 JavaScript Library

on:
  push:
    branches:
      - master

jobs:
  process:
    name: library release process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install and test
        run: |
          yarn install
          yarn test
          ./bin/d2-style js check --all
      - name: publish to npm
        run: npx @dhis2/cli-utils release --publish npm
        env:
          GIT_AUTHOR_NAME: "@dhis2-bot"
          GIT_AUTHOR_EMAIL: "apps@dhis2.org"
          GIT_COMMITTER_NAME: "@dhis2-bot"
          GIT_COMMITTER_EMAIL: "apps@dhis2.org"
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
