name: 'dhis2: static analysis'

#
# The base directory can be configured with:
# with:
#   projectBaseDir: my-custom-directory
#
# In the base directory, the file sonar-project.properties must exist with the following properties:
#
# sonar.organization=<replace with your SonarCloud organization key>
# sonar.projectKey=<replace with the key generated when setting up the project on SonarCloud>
# sonar.sources=.
#

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

env:
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    SONAR_TOKEN: ${{ secrets.DHIS2_BOT_SONARCLOUD_TOKEN }}

jobs:
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ env.GH_TOKEN }}
                  SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
